### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by NiJoMa** [douira/resolution-editor#1]
C:\Users\Nils\Desktop\re>node ./bin/www
module.js:471
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Nils\Desktop\re\app.js:1:
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by NiJoMa** [comment]
Solved
