### ISSUE TITLE
Server crash on page close because of LieView ws

### ISSUE THREAD

**Issue by douira** [douira/resolution-editor#119]
This stack trace belongs to an error that (probably) occurred when the editor page was closed and the resolution was in stage 1. The editor had been opened in MA mode and LV was on because of that. It seems like `tokenEntry`is undefined when there are no clients. (+ other necessary circumstances?)
```
tokenEntry.viewersForEach((v) => sendJson(v.socket, { type: "editorGone" }));
                  ^
TypeError: Cannot read property 'viewersForEach' of undefined
    at WebSocket.ws.on (/.../lib/liveView.js:652:19)
    at emitTwo (events.js:130:20)
    at WebSocket.emit (events.js:213:7)
    at ...
```

**Comment by douira** [comment]
It may be worth noting that this also happened when the editor was a tab in the background.
