### ISSUE TITLE
Amendment update crashes liveview on server

### ISSUE THREAD

**Issue by douira** [douira/resolution-editor#124]
```
resolution-editor/routes/liveview.js:234
      } else if (prop in obj.diff) {
                      ^
TypeError: Cannot use 'in' operator to search for 'content' in undefined
at markConsistentDiffs (resolution-editor/routes/liveview.js:234:23)
at markConsistentDiffs (resolution-editor/routes/liveview.js:228:24)
at markConsistentDiffs (resolution-editor/routes/liveview.js:228:24)
at processMessage (resolution-editor/routes/liveview.js:488:13)
at WebSocket.ws.on (resolution-editor/routes/liveview.js:585:9)
```
![screen shot 2018-02-21 at 20 12 12](https://user-images.githubusercontent.com/17120022/36500098-953c81ae-1743-11e8-804f-8d768a926357.png)
The server crashes with this error after receiving a structure update followed by an accompanying amendment update when the selected amendment clause has subclauses and is moved (up/down).

**Comment by douira** [comment]
This seems to only affects top level op clauses.

**Comment by douira** [comment]
Can't reproduce on external-data branch right now.
